# Generated by Django 4.0.4 on 2022-04-29 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('url_ticketmaster', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
