# Generated by Django 4.0.4 on 2022-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='user_avatar',
            name='events',
            field=models.ManyToManyField(blank=True, to='main_app.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url_ticketmaster',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
