# Generated by Django 4.0.4 on 2022-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_event_user_user_avatar_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_avatar',
            name='bio',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
