# Generated by Django 4.0.4 on 2022-05-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url_ticketmaster',
        ),
        migrations.CreateModel(
            name='TicketMasterEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.event')),
                ('url_ticketmaster', models.CharField(max_length=100, unique=True)),
            ],
            bases=('main_app.event',),
        ),
    ]
