# Generated by Django 4.0.4 on 2022-05-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('M', 'Music'), ('V', 'Visual Arts'), ('P', 'Performing Arts'), ('FI', 'Film'), ('L', 'Lectures'), ('FA', 'Fashion'), ('FD', 'Food and Drink'), ('FF', 'Festivals and Fairs'), ('C', 'Charities'), ('S', 'Sports'), ('N', 'Nightlife'), ('KF', 'Kids and Family'), ('O', 'Others')], default='M', max_length=100),
        ),
    ]
