# Generated by Django 4.0.4 on 2022-05-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=1, verbose_name='comment date'),
            preserve_default=False,
        ),
    ]
