# Generated by Django 4.0.4 on 2022-05-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_comment_options_remove_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
    ]
