# Generated by Django 4.0.4 on 2022-05-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
